[build]
  cmd = "go build -o tmp/movietracker.exe ./cmd/movietracker"
  bin = "tmp/movietracker.exe"
  full_bin = "tmp/movietracker.exe"
  include_ext = ["go", "toml"]
  exclude_dir = ["tmp", "vendor", "testdata"]
  delay = 1000

[log]
  time = true

[misc]
  clean_on_exit = true
