// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type Medium struct {
	ID                 int64
	Filename           string
	FolderRelativePath string
	FileSizeBytes      int64
	CurrentStatus      string
	OnDisk             int64
	CreatedAt          time.Time
}

type StartEvent struct {
	ID        int64
	MediaID   int64
	StartedAt time.Time
}

type StatusChange struct {
	ID         int64
	MediaID    int64
	FromStatus sql.NullString
	ToStatus   string
	ChangedAt  time.Time
}

type TreeState struct {
	FolderPath string
	Expanded   int64
}
