// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
)

const countOnDisk = `-- name: CountOnDisk :one
SELECT COUNT(*) FROM media WHERE on_disk = 1
`

func (q *Queries) CountOnDisk(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOnDisk)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listOnDiskMedia = `-- name: ListOnDiskMedia :many
SELECT id, filename, folder_relative_path, file_size_bytes, current_status, on_disk, created_at
FROM media
WHERE on_disk = 1
ORDER BY folder_relative_path, filename
`

func (q *Queries) ListOnDiskMedia(ctx context.Context) ([]Medium, error) {
	rows, err := q.db.QueryContext(ctx, listOnDiskMedia)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Medium
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.FolderRelativePath,
			&i.FileSizeBytes,
			&i.CurrentStatus,
			&i.OnDisk,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllOffDisk = `-- name: MarkAllOffDisk :exec
UPDATE media SET on_disk = 0
`

func (q *Queries) MarkAllOffDisk(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, markAllOffDisk)
	return err
}

const upsertMedia = `-- name: UpsertMedia :one
INSERT INTO media (filename, folder_relative_path, file_size_bytes, on_disk)
VALUES (?, ?, ?, 1)
ON CONFLICT(filename, file_size_bytes) DO UPDATE SET
    folder_relative_path = excluded.folder_relative_path,
    on_disk = 1
RETURNING id
`

type UpsertMediaParams struct {
	Filename           string
	FolderRelativePath string
	FileSizeBytes      int64
}

func (q *Queries) UpsertMedia(ctx context.Context, arg UpsertMediaParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertMedia, arg.Filename, arg.FolderRelativePath, arg.FileSizeBytes)
	var id int64
	err := row.Scan(&id)
	return id, err
}
