// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const countOnDisk = `-- name: CountOnDisk :one
SELECT COUNT(*) FROM media WHERE on_disk = 1
`

func (q *Queries) CountOnDisk(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOnDisk)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getMediaByID = `-- name: GetMediaByID :one
SELECT id, filename, folder_relative_path, file_size_bytes, current_status, on_disk, created_at, file_created_at, translation_type
FROM media WHERE id = ?
`

func (q *Queries) GetMediaByID(ctx context.Context, id int64) (Medium, error) {
	row := q.db.QueryRowContext(ctx, getMediaByID, id)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.FolderRelativePath,
		&i.FileSizeBytes,
		&i.CurrentStatus,
		&i.OnDisk,
		&i.CreatedAt,
		&i.FileCreatedAt,
		&i.TranslationType,
	)
	return i, err
}

const getStartEvents = `-- name: GetStartEvents :many
SELECT id, media_id, started_at
FROM start_events
WHERE media_id = ?
ORDER BY started_at DESC
`

func (q *Queries) GetStartEvents(ctx context.Context, mediaID int64) ([]StartEvent, error) {
	rows, err := q.db.QueryContext(ctx, getStartEvents, mediaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StartEvent
	for rows.Next() {
		var i StartEvent
		if err := rows.Scan(&i.ID, &i.MediaID, &i.StartedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStatusChanges = `-- name: GetStatusChanges :many
SELECT id, media_id, from_status, to_status, changed_at
FROM status_changes
WHERE media_id = ?
ORDER BY changed_at DESC
`

func (q *Queries) GetStatusChanges(ctx context.Context, mediaID int64) ([]StatusChange, error) {
	rows, err := q.db.QueryContext(ctx, getStatusChanges, mediaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StatusChange
	for rows.Next() {
		var i StatusChange
		if err := rows.Scan(
			&i.ID,
			&i.MediaID,
			&i.FromStatus,
			&i.ToStatus,
			&i.ChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertStartEvent = `-- name: InsertStartEvent :exec
INSERT INTO start_events (media_id) VALUES (?)
`

func (q *Queries) InsertStartEvent(ctx context.Context, mediaID int64) error {
	_, err := q.db.ExecContext(ctx, insertStartEvent, mediaID)
	return err
}

const insertStatusChange = `-- name: InsertStatusChange :exec
INSERT INTO status_changes (media_id, from_status, to_status) VALUES (?, ?, ?)
`

type InsertStatusChangeParams struct {
	MediaID    int64
	FromStatus sql.NullString
	ToStatus   string
}

func (q *Queries) InsertStatusChange(ctx context.Context, arg InsertStatusChangeParams) error {
	_, err := q.db.ExecContext(ctx, insertStatusChange, arg.MediaID, arg.FromStatus, arg.ToStatus)
	return err
}

const listAllMedia = `-- name: ListAllMedia :many
SELECT id, filename, folder_relative_path, file_size_bytes, current_status, on_disk, created_at, file_created_at, translation_type
FROM media
ORDER BY folder_relative_path, filename
`

func (q *Queries) ListAllMedia(ctx context.Context) ([]Medium, error) {
	rows, err := q.db.QueryContext(ctx, listAllMedia)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Medium
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.FolderRelativePath,
			&i.FileSizeBytes,
			&i.CurrentStatus,
			&i.OnDisk,
			&i.CreatedAt,
			&i.FileCreatedAt,
			&i.TranslationType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOnDiskMedia = `-- name: ListOnDiskMedia :many
SELECT id, filename, folder_relative_path, file_size_bytes, current_status, on_disk, created_at, file_created_at, translation_type
FROM media
WHERE on_disk = 1
ORDER BY folder_relative_path, filename
`

func (q *Queries) ListOnDiskMedia(ctx context.Context) ([]Medium, error) {
	rows, err := q.db.QueryContext(ctx, listOnDiskMedia)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Medium
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.FolderRelativePath,
			&i.FileSizeBytes,
			&i.CurrentStatus,
			&i.OnDisk,
			&i.CreatedAt,
			&i.FileCreatedAt,
			&i.TranslationType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllOffDisk = `-- name: MarkAllOffDisk :exec
UPDATE media SET on_disk = 0
`

func (q *Queries) MarkAllOffDisk(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, markAllOffDisk)
	return err
}

const updateMediaStatus = `-- name: UpdateMediaStatus :exec
UPDATE media SET current_status = ? WHERE id = ?
`

type UpdateMediaStatusParams struct {
	CurrentStatus string
	ID            int64
}

func (q *Queries) UpdateMediaStatus(ctx context.Context, arg UpdateMediaStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateMediaStatus, arg.CurrentStatus, arg.ID)
	return err
}

const updateTranslationType = `-- name: UpdateTranslationType :exec
UPDATE media SET translation_type = ? WHERE id = ?
`

type UpdateTranslationTypeParams struct {
	TranslationType string
	ID              int64
}

func (q *Queries) UpdateTranslationType(ctx context.Context, arg UpdateTranslationTypeParams) error {
	_, err := q.db.ExecContext(ctx, updateTranslationType, arg.TranslationType, arg.ID)
	return err
}

const upsertMedia = `-- name: UpsertMedia :one
INSERT INTO media (filename, folder_relative_path, file_size_bytes, on_disk, file_created_at, translation_type)
VALUES (?, ?, ?, 1, ?, ?)
ON CONFLICT(filename, file_size_bytes) DO UPDATE SET
    folder_relative_path = excluded.folder_relative_path,
    on_disk = 1,
    file_created_at = COALESCE(media.file_created_at, excluded.file_created_at),
    -- Keep an existing (manually set or previously detected) translation type;
    -- only fill in the detected hint when the current value is still empty.
    translation_type = CASE WHEN media.translation_type != '' THEN media.translation_type ELSE excluded.translation_type END
RETURNING id
`

type UpsertMediaParams struct {
	Filename           string
	FolderRelativePath string
	FileSizeBytes      int64
	FileCreatedAt      sql.NullTime
	TranslationType    string
}

func (q *Queries) UpsertMedia(ctx context.Context, arg UpsertMediaParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertMedia,
		arg.Filename,
		arg.FolderRelativePath,
		arg.FileSizeBytes,
		arg.FileCreatedAt,
		arg.TranslationType,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
